# Generated by Django 5.1.4 on 2025-01-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosp_name', models.CharField(max_length=255)),
                ('hosp_address', models.TextField()),
                ('hosp_city', models.CharField(max_length=100)),
                ('hosp_district', models.CharField(max_length=100)),
                ('hosp_state', models.CharField(max_length=100)),
                ('hosp_contact', models.CharField(max_length=15)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imfapp.login')),
            ],
        ),
    ]
