# Generated by Django 5.1.4 on 2025-01-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='usertype',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
