# Generated by Django 5.1.4 on 2025-01-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0003_alter_login_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalregister',
            name='hosp_address',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DoctorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('doc_license', models.FileField(upload_to='license')),
                ('hosp_id', models.CharField(max_length=100)),
                ('doc_contact', models.IntegerField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imfapp.login')),
            ],
        ),
    ]
