# Generated by Django 5.1.4 on 2025-01-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0004_alter_hospitalregister_hosp_address_doctorregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregister',
            name='doc_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctorregister',
            name='hosp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosp_id', to='imfapp.login'),
        ),
        migrations.AlterField(
            model_name='doctorregister',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_id', to='imfapp.login'),
        ),
    ]
