# Generated by Django 5.1.4 on 2025-01-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0005_alter_doctorregister_doc_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalRegister',
        ),
    ]
