# Generated by Django 5.1.4 on 2025-01-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0006_delete_hospitalregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosp_name', models.CharField(max_length=255)),
                ('hosp_address', models.CharField(max_length=255)),
                ('hosp_city', models.CharField(max_length=100)),
                ('hosp_district', models.CharField(max_length=100)),
                ('hosp_state', models.CharField(max_length=100)),
                ('hosp_contact', models.CharField(max_length=15)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imfapp.login')),
            ],
        ),
    ]
