# Generated by Django 5.1.4 on 2025-02-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0008_patientregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientRegister',
        ),
    ]
