# Generated by Django 5.1.4 on 2025-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0010_patientregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='patient_contact',
            field=models.CharField(max_length=20),
        ),
    ]
