# Generated by Django 5.1.4 on 2025-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0011_alter_patientregister_patient_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='department',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='specialisation',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
