# Generated by Django 5.1.4 on 2025-02-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0012_doctorregister_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_login', to='imfapp.login')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_login', to='imfapp.login')),
            ],
        ),
    ]
