# Generated by Django 5.1.4 on 2025-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0014_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregister',
            name='consultation_fee',
            field=models.IntegerField(default=0),
        ),
    ]
