# Generated by Django 5.1.4 on 2025-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0015_alter_doctorregister_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
