# Generated by Django 5.1.4 on 2025-03-01 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0016_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('exp_date', models.CharField(max_length=255)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imfapp.appointment')),
            ],
        ),
    ]
