# Generated by Django 5.1.4 on 2025-03-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_status',
            field=models.IntegerField(default=0),
        ),
    ]
