# Generated by Django 5.1.6 on 2025-03-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0018_appointment_cancel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_category', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_no', models.CharField(max_length=255)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_contact', models.CharField(max_length=15)),
                ('amb_login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amb_login_id', to='imfapp.login')),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosp_loginid', to='imfapp.login')),
            ],
        ),
    ]
