# Generated by Django 5.1.4 on 2025-03-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0018_appointment_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='refund_status',
            field=models.IntegerField(default=0),
        ),
    ]
