# Generated by Django 5.1.6 on 2025-03-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0019_ambulanceregister'),
        ('imfapp', '0019_appointment_refund_status'),
    ]

    operations = [
    ]
