# Generated by Django 5.1.4 on 2025-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0020_merge_20250304_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
