# Generated by Django 5.1.4 on 2025-03-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfapp', '0021_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_status',
            field=models.IntegerField(default=0),
        ),
    ]
